version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: sawyer-backend
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
    command: ["/start.sh"]

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile.frontend
    container_name: sawyer-frontend
    ports:
      - "5173:5173"

